menu:
  # Archives: /archives
  幻想间: /favourite
  # 时光机: /timeline
  # 幻想间: /favourite/image.html
  关于我: /aboutme
rss: /atom.xml
description: 
social:
  weibo: https://weibo.com/p/1005053430067690/home
  github: https://github.com/Gsl201600
  stack_overflow: 
  facebook: https://www.facebook.com/guan.shuaile.334
  twitter: https://twitter.com/wrSIuYLrNzKhNoc
  google_plus: 

page_comment: true
logo: /images/avatar.png
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: UA-78918255-1
baidu_tongji: 9cdad07c755fa23f6aced510c6760e87
favicon: /images/avatar-small.ico

#mathjax
mathjax: true

# 'Read more' button
excerpt_link: 继续阅读

# Footer message
site_license: 本站点采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>
theme_message: 本站由 <a href="https://gsl201600.github.io">@gsl</a> 创建，基于 <a href="http://hexo.io">Hexo</a> 搭建，使用 <a href="https://github.com/monniya/hexo-theme-new-vno ">new-vno</a> 主题，原创出自<a href="http://github.com/onevcat/vno" target="_blank">onevcat</a>

